### ISSUE TITLE
SDb如何实现跨服务器联表查询呢？

### ISSUE THREAD

**Issue by jbkingsley** [hetao29/slightphp#2]
如何，LOG数据库一般都是单独存放的，现在碰到需要联查另外一台服务器上的用户库里的用户信息，不知道该怎么写呢？

**Comment by hetao29** [comment]
跨库的话，建议用2个SDb类操作，一个取出要跨表的多个id，再从另一个库里用id查数据，联查是不可能的。

2016-04-08 16:45 GMT+08:00 jbkingsley notifications@github.com:
