### ISSUE TITLE
entry 映射为方法名，以Page开头的方法名中Page的P是大写还是小写？

### ISSUE THREAD

**Issue by csk83** [hetao29/slightphp#2]
Page在README.MD里面是大写
在SlightPHP.php 里面是大写
在例子里面小写
c里面也是小写

到底用那种呢？

好像通常是
ClassName
{
     function myMethod(){}
}

这里
class_name
{
     function MyMethod(){}
}

感觉奇怪

**Comment by hetao29** [comment]
类名用_分开，方便autoload，方法名是用的驼峰式的

何涛 Hetal

Tel: 13488810858

北京市海淀区，100080




2015-03-03 12:56 GMT+08:00 csk83 <notifications@github.com>:

**Comment by csk83** [comment]
以Page开头的方法名中PageXXX的P是大写还是小写？

**Comment by hetao29** [comment]
方法名不区分大小写，看自己的习惯

何涛 Hetal

Tel: 13488810858

北京市海淀区，100080




2015-03-03 14:49 GMT+08:00 csk83 <notifications@github.com>:
