### ISSUE TITLE
slightPHP用于长链接应用的情形

### ISSUE THREAD

**Issue by jbkingsley** [hetao29/slightphp#4]
因比较喜欢slightPHP的框架处理方式，最近在一个Workman的 长链接应用 中也使用了slightphp，基本逻辑就是根据URI到响应的page文件里面处理业务。碰到一个问题不知道是什么原因：

**Comment by hetao29** [comment]
http://stackoverflow.com/questions/14748499/fatal-error-too-many-open-files

**Comment by hetao29** [comment]
你的问题有可能是程序里没有关闭一些打开的文件，可以根据如下方法找一下，也有可能是系统设置打开的文件太低
1. ps aux |grep php，找到你的程序的pid
2. lsof -p xxx ，查看你的这个程序打开了哪些文件，多少不
