### ISSUE TITLE
slightPHP用于长链接应用时碰到一个问题

### ISSUE THREAD

**Issue by jbkingsley** [hetao29/slightphp#5]
因比较喜欢slightPHP的框架处理方式，最近在一个Workman的 长链接应用 中也使用了slightphp，基本逻辑就是根据URI到响应的page文件里面处理业务。碰到一个问题不知道是什么原因：
1. 表面上的功能正常
2. 一次我调试完成后，没有关闭客户端，因为客户端在不停的发送心跳包，结果第二天发现出现了“Warning: slightphp::run(/Users/Sites/YS/Work/app/cloud/device.page.php): failed to open stream: Too many open files ”的错误警告
3. 此时只有一个连接的

不知是我对于slightPHP有哪里地方理解不对的吗？

**Comment by hetao29** [comment]
一、你的问题有可能是程序里没有关闭一些打开的文件，可以根据如下方法找一下
1. ps aux |grep php，找到你的程序的pid
2. lsof -p xxx ，查看你的这个程序打开了哪些文件，多少不

二、也有可能是系统设置打开的文件太低
根据下面的方法解决
http://stackoverflow.com/questions/14748499/fatal-error-too-many-open-files

**Comment by jbkingsley** [comment]
@hetao29
用上面的方法检查过，没有查到相关打开的文件
我正在做一些测试，怀疑是我用了pecl的slightphp的原因，好像是pecl打开了page文件后没有回收之类的情况

**Comment by hetao29** [comment]
我测试一下看看，如果pecl的没有关闭，其实lsof也能看到，你用的是workerman，可以用 php xxx status看到真实的pid

**Comment by hetao29** [comment]
我这发现这个问题了，立马修复

**Comment by hetao29** [comment]
php5.x解决了，php7.x还在解决中

**Comment by jbkingsley** [comment]
好的，我继续等等php7，可惜我自己不会弄~~~~~~

**Comment by hetao29** [comment]
php7 已经解决了[fixed](https://github.com/hetao29/slightphp/commit/e9f6d6d177b85de6a1ea964d733c912eb596ca63)

**Comment by hetao29** [comment]
可以再用用，有问题随时候沟通
