### ISSUE TITLE
php7报错

### ISSUE THREAD

**Issue by ecator** [hetao29/slightphp#6]
您好，以前用您的框架写了一个小应用，在php5的环境下能正常运行，最近准备迁移到php7上，但是到php7上一开始就报了一个奇怪的错误：

```
 Parse error: syntax error, unexpected '<', expecting end of file in /srv/www/bt-search/runtime/aW5kZXgudHBs.%%.tpl on line 1
```

查看上面生成的**tpl**文件内容也非常奇怪
```
<?php <; ?><?php !; ?><?php d; ?><?php o; ?><?php c; ?><?php t; ?><?php y; ?><?php p; ?><?php e; ?> <?php h; ?><?php t; ?><?php m; ?><?php l; ?><?php >; ?>
<?php <; ?><?php h; ?><?php t; ?><?php m; ?><?php l; ?> <?php l; ?><?php a; ?><?php n; ?><?php g; ?><?php =; ?><?php "; ?><?php e; ?><?php n; ?><?php "; ?><?php >; ?>
<?php <; ?><?php h; ?><?php e; ?><?php a; ?><?php d; ?><?php >; ?>
    <?php {; ?><?php i; ?><?php n; ?><?php c; ?><?php l; ?><?php u; ?><?php d; ?><?php e; ?> <?php "; ?><?php h; ?><?php e; ?><?php a; ?><?php d; ?><?php .; ?><?php t; ?><?php p; ?><?php l; ?><?php "; ?><?php }; ?>
```

差不错一年没有更新了，所以没有动以前的代码，就直接在php7的环境上跑的，目前我也不知道是不是对php7支持得还不是很好？

工程地址[https://github.com/ecator/bt-search](https://github.com/ecator/bt-search)
入口文件是 `public/index.php` 

---
再次感谢您的框架，本来我也准备放弃迁移到php7了，但是看到您的模版貌似还在更新，所以就抱着试一试的心态发个issue了，如果可能，希望您能帮我看看这个问题。 :relaxed:

**Comment by hetao29** [comment]
你只需要把 fetch 换成 render 就可以了
```php
return $this->render("index.tpl");
```

**Comment by ecator** [comment]
感谢回答，改成render后就行了

**Comment by hetao29** [comment]
https://github.com/hetao29/slightphp/commit/da1a977cc1f79d75e0e08919d68e05c0e84fd4ee
主要是这个改动，把分隔符放到了 STpl 里，没有放到 Tpl 类里，你直接调用 fetch，实际上使用的是 Tpl::fetch 这个方法，没有设置分隔符，就会把每个字符分割开
