### ISSUE TITLE
SlightPHP.php Line278代码优化问题

### ISSUE THREAD

**Issue by 1itt1eB0y** [hetao29/slightphp#9]
虽然看`readme`和已关闭的`issue`发现这个框架确实挺老的吧……但是现在刚好初学一些php的内容这个框架的逻辑结构我目前还是受益匪浅的。
然后就是一个简单的小bug，今天尝试的时候发现的。
README的部署中说直接访问`http://localhost/index.php`即可访问到对应的`defaultZone/defaultPage/detaultEntry`下，但是实际访问的时候发现只有访问`http://localhost/index.php/`才能实现跳转
在`SlightPHP.php`的`Line278`

> `$zone	= !empty($path_array[0]) ? $path_array[0] : self::$defaultZone ;`

导致访问时会出现对`http://localhost/index.php`的请求报`file[./index.php/page.page.php] does not exists`的错误，此时`$path_array[0]`由于没有分隔符导致错误接收了`index.php`
修改后代码如下

> `$zone	= !empty($path_array[0]) ? ($path_array[0] == 'index.php' ? self::$defaultZone : $path_array[0]) : self::$defaultZone ;`

判段当传入的`$path_array[0]`的参数为`index.php`时，将`$zone`转化为`self::$defaultZone`
谢谢作者的这个框架，为初学的我提供了不少学习案例和思路，目前只看到这个，如果这个是我个人的使用错误也谢谢作者啦！

**Comment by hetao29** [comment]
你参考 sample 部署你的 app 试试
